### ISSUE TITLE
❔: Is it possible to install this on any other DE

### ISSUE THREAD

**Issue by nandgator** [ZorinOS/gnome-shell-extension-zorin-connect#3]
I'm aware that this is a gnome extension, but for curiosity sake, can I install Zorin Connect on Pantheon / XFCE desktop?

**Comment by ArtyomZorin** [comment]
This extension works only with Gnome Shell. However, you should be able to install the upstream KDE Connect client in order to use Zorin Connect on other desktop environments like XFCE and Pantheon. This is possible because Zorin Connect uses the same protocol as KDE Connect.

You can install the KDE Connect client by entering this command (in Ubuntu-based distros):
`sudo apt install kdeconnect`

**Comment by nandgator** [comment]
Oh so I can connect Zorin Connect (Android) to KDE Connect (Ubuntu). Thanks!
